/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8TYVxsSP7QVMdpZV83f59e

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantskBQlKEyr93R } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: kBQlK_EYR93r/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantskBQlKEyr93R
});
